# docker-compose.yml
version: '3.1'
volumes:
    prometheus_data: {}
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/alert.rules:/etc/prometheus/alert.rules
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - '9090:9090'
        links:
            - alertmanager:alertmanager
    node-exporter:
        image: prom/node-exporter
        volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        command: 
        - '--path.procfs=/host/proc' 
        - '--path.sysfs=/host/sys'
        - --collector.filesystem.ignored-mount-points
        - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
        ports:
        - 9100:9100
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        volumes:
            - ./grafana_data:/var/lib/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=foobar
            - GF_USERS_ALLOW_SIGN_UP=false
    zipkin_storage:
        image: openzipkin/zipkin-elasticsearch6
        container_name: elasticsearch
    zipkin:
        image: openzipkin/zipkin
        environment:
            - STORAGE_TYPE=elasticsearch
            # Point the zipkin at the storage backend
            - ES_HOSTS=elasticsearch
            # Uncomment to see requests to and from elasticsearch
            # - ES_HTTP_LOGGING=BODY
        ports:
            - 9411:9411
    alertmanager:
        image: prom/alertmanager
        ports:
        - 9093:9093
        volumes:
        - ./alertmanager/:/etc/alertmanager/
        command:
        - '--config.file=/etc/alertmanager/alertmanager.yml'
        - '--storage.path=/alertmanager'
    cadvisor:
        image: google/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8080:8080
    pixel:
        image: pixel-api
        ports:
            - 5000:5000
        environment:
            - ZIPKIN_SERVER=http://zipkin:9411
            - VERBOSE=true

