{
 "title": "Pixel Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(http_request_failed_count{job=\"pixel-api\",method=\"pixel\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(http_request_duration_milliseconds_count{job=\"pixel-api\",method=\"pixel\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_milliseconds_sum{job=\"pixel-api\",method=\"pixel\"}[1m])))/(sum(rate(http_request_duration_milliseconds_count{job=\"pixel-api\",method=\"pixel\"}[1m])))"
    }
   ]
  },
  {
   "title": "Quantile",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_milliseconds_bucket{job=\"pixel-api\",method=\"pixel\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_milliseconds_sum{job=\"pixel-api\",method=\"pixel\"}[1m])))/(sum(rate(http_request_duration_milliseconds_count{job=\"pixel-api\",method=\"pixel\"}[1m])))"
    }
   ]
  },
  {
   "title": "Quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_milliseconds_bucket{job=\"pixel-api\",method=\"pixel\"}[1m]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.8, rate(http_request_duration_milliseconds_bucket{job=\"pixel-api\",method=\"pixel\"}[1m]))",
     "legendFormat": "0.8"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_milliseconds_bucket{job=\"pixel-api\",method=\"pixel\"}[1m]))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_milliseconds_bucket{job=\"pixel-api\",method=\"pixel\"}[1m]))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Failed Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_failed_count{job=\"pixel-api\",method=\"pixel\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_milliseconds_count{job=\"pixel-api\",method=\"pixel\"}[1m])"
    }
   ]
  }
 ]
}